// Generated by CoffeeScript 1.4.0
(function() {
  var FIREBASE_URL, createRoom;

  FIREBASE_URL = "https://whereareyou.firebaseio.com/v1";

  createRoom = function() {
    var child, firebase;
    firebase = new Firebase(FIREBASE_URL);
    child = firebase.push();
    return document.location = document.location + child.name();
  };

  createRoom();

}).call(this);
